name = "anni-lumao-diary"
compatibility_date = "2024-01-01"

[env.production]
name = "anni-lumao-diary"

[[env.production.d1_databases]]
binding = "DB"
database_name = "anni-lumao-diary-db"
database_id = "your-database-id-here"

[env.preview]
name = "anni-lumao-diary-preview"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "anni-lumao-diary-db-preview"
database_id = "your-preview-database-id-here"
